---
- include: requeriments.yml
- name: Install PHP with Modules and git
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - php7.0
    - php7.0-xmlrpc
    - php7.0-zip
    - php7.0-simplexml
    - php7.0-intl
    - php7.0-pgsql
    - php7.0-curl
    - php7.0-gd
    - php7.0-mbstring
    - php7.0-soap
    - libapache2-mod-php7.0
    - git

- name: Install Apache and dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make
    - perl
    - apache2

- name: Start Apache Service
  service:
    name: apache2
    state: started

- name: Create user
  user: name="{{ moodle_user }}"

- name: Create moodle directry
  file: dest="{{ moodle_path }}" state=directory owner="{{ moodle_user }}"


- name: Getting Moodle
  git: repo=https://github.com/moodle/moodle.git version="{{ moodle_version }}" dest="{{ moodle_src }}" accept_hostkey=yes

- name: Configure Moodle
  template: src=config.php.j2 dest="{{ moodle_src }}/config.php"

- name: Create moodle docs directry
  file: dest="{{ moodle_docs }}" state=directory owner="{{ moodle_user }}"
