---
- name: Ensure python-apt is installed
  command: apt-get update
  command: apt-get install python-apt -y -q
  sudo: yes

- name: Install requeriments
  apt: name="{{ item }}"
  with_items:
    - git
    - php7.0-mysql
    - php7.0-intl
    - php7.0-xmlrpc
    - php7.0-fpm
  notify: [ 'Restart php7.0-fpm' ]
