---
galaxy_info:
  author: Whoever
  description: "MySQL"
  company: your company (optional)
  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2


  platforms:
    - name: Ubuntu
      versions:
        - xenial
  galaxy_tags:
    - database
    - mysql

  dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
